#!/usr/bin/env bash
# Check if exactly one argument was passed
if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the received IP address exactly 5 times
ping -c 5 "$1"
